# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://hectorcarrion.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Héctor Carrión"
